[package]
name = "devices"
version = "0.1.0"
authors = ["rust-vmm AWS maintainers <rust-vmm-maintainers@amazon.com>"]
edition = "2018"
license = "Apache-2.0 OR BSD-3-Clause"

[dependencies]
event-manager = { version = "0.2.0", features = ["remote_endpoint"] }
kvm-ioctls = "0.5.0"
libc = "0.2.76"
log = "0.4.6"
vm-memory = "0.3.0"
vmm-sys-util = "0.6.1"

vm-device = { git = "https://github.com/rust-vmm/vm-device.git" }
vm-virtio = { git = "https://github.com/rust-vmm/vm-virtio.git" }

